// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'apps/api/src/database/schema.prisma',
  migrations: {
    path: 'apps/api/src/database/migrations',
    seed: 'ts-node apps/api/src/database/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
