import {
  Prisma,
  SessionPreference as PrismaSessionPreference,
} from '@prisma/client';
import { DietaryTag, MealSession, Taste } from '../../../products';
import { SessionPreference } from './session-preference';
import { MissingRequireFieldsException } from '../../../../common/exceptions';

export class SessionPreferenceMapper {
  /**
   * Converts a Prisma {@link PrismaSessionPreference} row into a domain
   * {@link SessionPreference} instance.
   *
   * This method ensures that the domain layer receives a clean, structured object
   * that is independent of the database implementation. `Decimal` fields are
   * converted to `number`, and related entities like `favoriteCuisines` are
   * handled.
   *
   * @param prisma - The raw Prisma row returned from the database,
   * potentially including related entities.
   * @returns A hydrated {@link SessionPreference} domain entity.
   */
  static toDomain(prisma: PrismaSessionPreference): SessionPreference {
    return new SessionPreference(
      prisma.id,
      prisma.session_id,
      prisma.favorite_cuisines || [],
      prisma.favorite_meal_sessions as MealSession[],
      prisma.favorite_taste_profile as Taste[],
      prisma.dietary_restrictions as DietaryTag[],
      prisma.avg_spice_preference ? Number(prisma.avg_spice_preference) : null,
      prisma.avg_price_range ? Number(prisma.avg_price_range) : null,
      prisma.order_count,
      prisma.last_order_date,
      prisma.created_at,
      prisma.updated_at,
    );
  }

  /**
   * Converts a domain {@link SessionPreference} entity into a Prisma
   * {@link Prisma.SessionPreferenceUncheckedCreateInput} payload, suitable for
   * `create` operations.
   *
   * Note: The `id` is omitted as it is auto-generated by the database.
   *
   * @param domain - The domain entity to convert.
   * @returns The Prisma create-input payload.
   * @throws {MissingRequireFieldsException} If any required fields are missing in the domain entity.
   * @remarks Required fields for creation include: `sessionId`, `favoriteCuisines`, `favoriteMealSessions`,
   * `favoriteTasteProfile`, `dietaryRestrictions`, `avgSpicePreference`, `avgPriceRange`, and `orderCount`.
   */
  static toPrismaCreateInput(
    domain: SessionPreference,
  ): Prisma.SessionPreferenceUncheckedCreateInput {
    if (
      !domain.sessionId ||
      !domain.favoriteCuisines ||
      !domain.favoriteMealSessions ||
      !domain.favoriteTasteProfile ||
      !domain.dietaryRestrictions ||
      !domain.avgSpicePreference ||
      !domain.avgPriceRange ||
      !domain.orderCount
    ) {
      throw new MissingRequireFieldsException([
        'sessionId',
        'favoriteCuisines',
        'favoriteMealSessions',
        'favoriteTasteProfile',
        'dietaryRestrictions',
        'avgSpicePreference',
        'avgPriceRange',
        'orderCount',
      ]);
    }
    return {
      session_id: domain.sessionId,
      favorite_meal_sessions: domain.favoriteMealSessions,
      favorite_taste_profile: domain.favoriteTasteProfile,
      dietary_restrictions: domain.dietaryRestrictions,
      avg_spice_preference: domain.avgSpicePreference,
      avg_price_range: domain.avgPriceRange,
      order_count: domain.orderCount,
      last_order_date: domain.lastOrderDate,
    };
  }

  /**
   * Converts a partial domain {@link SessionPreference} entity into a Prisma
   * {@link Prisma.SessionPreferenceUncheckedUpdateInput} payload, suitable for
   * `update` operations.
   *
   * This method selectively includes only the fields present in the partial
   * entity, making it efficient for updates.
   *
   * @param entity - The partial domain entity containing fields to be updated.
   * @returns The Prisma update-input payload.
   */
  static toPrismaUpdateInput(
    entity: Partial<SessionPreference>,
  ): Prisma.SessionPreferenceUncheckedUpdateInput {
    const data: Prisma.SessionPreferenceUncheckedUpdateInput = {};
    if (entity.sessionId) {
      data.session_id = entity.sessionId;
    }
    if (entity.favoriteMealSessions) {
      data.favorite_meal_sessions = entity.favoriteMealSessions;
    }
    if (entity.favoriteTasteProfile) {
      data.favorite_taste_profile = entity.favoriteTasteProfile;
    }
    if (entity.dietaryRestrictions) {
      data.dietary_restrictions = entity.dietaryRestrictions;
    }
    if (entity.avgSpicePreference) {
      data.avg_spice_preference = entity.avgSpicePreference;
    }
    if (entity.avgPriceRange) {
      data.avg_price_range = entity.avgPriceRange;
    }
    if (entity.orderCount) {
      data.order_count = entity.orderCount;
    }
    if (entity.lastOrderDate) {
      data.last_order_date = entity.lastOrderDate;
    }
    return data;
  }
}
