/**
 * Represents a forecasted usage of an ingredient for a specific date.
 * Generated by the Prophet model and stored for inventory planning.
 *
 * @param id Unique identifier for the forecast record.
 * @param ingredientId Foreign key referencing the associated Ingredient.
 * @param forecastDate The calendar date for which the forecast applies.
 * @param predictedUsage Predicted quantity of the ingredient to be consumed on that date.
 * @param lowerBound Lower confidence interval bound of the prediction.
 * @param upperBound Upper confidence interval bound of the prediction.
 * @param confidenceLevel Confidence level for the prediction interval (e.g., 0.95 = 95%).
 * @param modelVersion Version string of the forecasting model that produced this record.
 * @param createdAt Timestamp when the forecast record was persisted.
 */
export class IngredientForecast {
  constructor(
    public id: string | null = null,
    public ingredientId: string,
    public forecastDate: Date,
    public predictedUsage: number,
    public lowerBound: number,
    public upperBound: number,
    public confidenceLevel: number,
    public modelVersion: string,
    public createdAt: Date | null = null,
  ) {}
}
